levels = [
    #{  
        #  'geometry': [   '    bbb   ',
        #                 '    bbb   ',
        #                 '    bbb   ',
        #                 '    bbb   ',
        #                 '    b     ',
        #                 '    b     ',
        #                 '  bbb     ',
        #                 '  bbbbb   ',
        #                 '  bbb     ',
        #                 '    b     ',
        #                 '          ',
        #                 '    b e   ',
        #                 '    b b   ',
        #                 '    b b   ',
        #                 '    v b   '],
        # 'start': {'x': 4, 'y': 11},
        # 'swatches': [   {   'fields': [   {   'action': 'split1',
        #                                       'position': {'x': 6, 'y': 12}},
        #                                   {   'action': 'split2',
        #                                       'position': {'x': 6, 'y': 14}}],
        #                     'position': {'x': 4, 'y': 14},
        #                     'type': 'v'}]},
    
       {   'geometry': [   '          ',
                        '          ',
                        '     bbb  ',
                        '    bbbb  ',
                        '    bbbb  ',
                        '    bbb   ',
                        '    bbb   ',
                        '   bbbb   ',
                        '  bbbb    ',
                        '  bebb    ',
                        '  bbbb    ',
                        '   bb     ',
                        '          ',
                        '          ',
                        '          '],
        'start': {'x': 6, 'y': 3},
        'swatches': []},
    {   'geometry': [   '   bbbbb  ',
                        '   bbbbb  ',
                        '   bbbsb  ',
                        '   bbbbb  ',
                        '    l     ',
                        '    r     ',
                        '   bbbbbb ',
                        '   bbbbbb ',
                        '   bbbbhb ',
                        '   bbbbbb ',
                        '    l     ',
                        '    r     ',
                        '    bbbbb ',
                        '    bbbeb ',
                        '    bbbbb '],
        'start': {'x': 4, 'y': 1},
        'swatches': [   {   'fields': [   {   'action': 'onoff',
                                              'position': {'x': 4, 'y': 10}},
                                          {   'action': 'onoff',
                                              'position': {'x': 4, 'y': 11}}],
                            'position': {'x': 7, 'y': 8},
                            'type': 'h'},
                        {   'fields': [   {   'action': 'onoff',
                                              'position': {'x': 4, 'y': 4}},
                                          {   'action': 'onoff',
                                              'position': {'x': 4, 'y': 5}}],
                            'position': {'x': 6, 'y': 2},
                            'type': 's'}]},
    {   'geometry': [   '   bbbb   ',
                        '   bbbb   ',
                        '   bbbb   ',
                        '   bbbb   ',
                        '     b    ',
                        '     b    ',
                        '     bbb  ',
                        '     bbb  ',
                        '     bbb  ',
                        '       b  ',
                        '       b  ',
                        '   bbbbb  ',
                        '  bbbbbb  ',
                        '  bbeb    ',
                        '  bbbb    '],
        'start': {'x': 4, 'y': 1},
        'swatches': []},
    {   'geometry': [   '  bbbbb   ',
                        '  bbbbb   ',
                        '  bbbbb   ',
                        '      bff ',
                        '       ff ',
                        'bbbb   ff ',
                        'bebb   ff ',
                        'bbbb   ff ',
                        '  bb   ff ',
                        '  ff  bff ',
                        'ffffbbb   ',
                        'ffffbbb   ',
                        'fbff      ',
                        'ffff      ',
                        '          '],
        'start': {'x': 3, 'y': 1},
        'swatches': []},
    {   'geometry': [   'bbb       ',
                        'beb  bbbb ',
                        'bbb  bbbb ',
                        'bb  bbsbb ',
                        ' b  bbbbb ',
                        ' k  b   k ',
                        ' q  s   q ',
                        ' b  b   b ',
                        ' b  k   s ',
                        ' b  q   b ',
                        ' bbbb   b ',
                        ' bbbb   bb',
                        ' bbbb  bbb',
                        '  bb   bbb',
                        '  bs   bbb'],
        'start': {'x': 8, 'y': 13},
        'swatches': [   {   'fields': [   {   'action': 'onoff',
                                              'position': {'x': 8, 'y': 6}},
                                          {   'action': 'onoff',
                                              'position': {'x': 8, 'y': 5}}],
                            'position': {'x': 8, 'y': 8},
                            'type': 's'},
                        {   'fields': [   {   'action': 'on',
                                              'position': {'x': 1, 'y': 5}},
                                          {   'action': 'on',
                                              'position': {'x': 1, 'y': 6}}],
                            'position': {'x': 6, 'y': 3},
                            'type': 's'},
                        {   'fields': [   {   'action': 'off',
                                              'position': {'x': 1, 'y': 5}},
                                          {   'action': 'off',
                                              'position': {'x': 1, 'y': 6}}],
                            'position': {'x': 4, 'y': 6},
                            'type': 's'},
                        {   'fields': [   {   'action': 'onoff',
                                              'position': {'x': 1, 'y': 5}},
                                          {   'action': 'onoff',
                                              'position': {'x': 1, 'y': 6}}],
                            'position': {'x': 3, 'y': 14},
                            'type': 's'}]},
    {   'geometry': [   '      b   ',
                        '      b   ',
                        '      b   ',
                        '      b   ',
                        '    bbb   ',
                        '    bbbbbb',
                        ' bbbbb   b',
                        'bbb      b',
                        'bbb    bbb',
                        'bbbb   bbb',
                        ' bbb   bbb',
                        '     bbb  ',
                        '    bbbb  ',
                        '    beb   ',
                        '    bbb   '],
        'start': {'x': 6, 'y': 0},
        'swatches': []},
    {   'geometry': [   '   bbbb   ',
                        '  bbbbb   ',
                        ' bbbbbb   ',
                        ' bl  b    ',
                        ' b   b    ',
                        ' b   b    ',
                        ' b   b    ',
                        ' bbbbb    ',
                        '   bbbbbb ',
                        '   bh  bb ',
                        '       bb ',
                        '      bbb ',
                        '   bbbb   ',
                        '   bbeb   ',
                        '   bbbb   '],
        'start': {'x': 5, 'y': 1},
        'swatches': [   {   'fields': [   {   'action': 'onoff',
                                              'position': {'x': 2, 'y': 3}}],
                            'position': {'x': 4, 'y': 9},
                            'type': 'h'}]},
    {   'geometry': [   '    bbb   ',
                        '    bbb   ',
                        '    bbb   ',
                        '    bbb   ',
                        '    bvb   ',
                        '    bbb   ',
                        '          ',
                        '          ',
                        '          ',
                        ' bbbbbbbbb',
                        ' bbbbbbbbb',
                        ' bbbbbbbbb',
                        '    bbb   ',
                        '    beb   ',
                        '    bbb   '],
        'start': {'x': 5, 'y': 1},
        'swatches': [   {   'fields': [   {   'action': 'split1',
                                              'position': {'x': 8, 'y': 10}},
                                          {   'action': 'split2',
                                              'position': {'x': 2, 'y': 10}}],
                            'position': {'x': 5, 'y': 4},
                            'type': 'v'}]},
    {   'geometry': [   '    bbb   ',
                        '    bbb   ',
                        '    bbb   ',
                        '    bbb   ',
                        '    b     ',
                        '    b     ',
                        '  bbb     ',
                        '  bebbb   ',
                        '  bbb     ',
                        '    b     ',
                        '    b     ',
                        '    bbb   ',
                        '    bbb   ',
                        '    bvb   ',
                        '    bbb   '],
        'start': {'x': 5, 'y': 1},
        'swatches': [   {   'fields': [   {   'action': 'split1',
                                              'position': {'x': 5, 'y': 12}},
                                          {   'action': 'split2',
                                              'position': {'x': 5, 'y': 2}}],
                            'position': {'x': 5, 'y': 13},
                            'type': 'v'}]},
    {   'geometry': [   '          ',
                        '       bbb',
                        '       beb',
                        '       bbb',
                        '        l ',
                        'bb      r ',
                        'sb      b ',
                        ' b      l ',
                        ' b      r ',
                        'bb     bbb',
                        'b     bbbb',
                        'b     bbbb',
                        'hbb  bbbbb',
                        'bbbbbbllvb',
                        '        bb'],
        'start': {'x': 8, 'y': 10},
        'swatches': [   {   'fields': [   {   'action': 'split1',
                                              'position': {'x': 8, 'y': 13}},
                                          {   'action': 'split2',
                                              'position': {'x': 8, 'y': 10}}],
                            'position': {'x': 8, 'y': 13},
                            'type': 'v'},
                        {   'fields': [   {   'action': 'onoff',
                                              'position': {'x': 8, 'y': 4}},
                                          {   'action': 'onoff',
                                              'position': {'x': 8, 'y': 5}}],
                            'position': {'x': 0, 'y': 6},
                            'type': 's'},
                        {   'fields': [   {   'action': 'onoff',
                                              'position': {'x': 8, 'y': 7}},
                                          {   'action': 'onoff',
                                              'position': {'x': 8, 'y': 8}},
                                          {   'action': 'onoff',
                                              'position': {'x': 7, 'y': 13}},
                                          {   'action': 'onoff',
                                              'position': {'x': 6, 'y': 13}}],
                            'position': {'x': 0, 'y': 12},
                            'type': 'h'}]},
    {   'geometry': [   '          ',
                        '          ',
                        '    b     ',
                        '    bbbbbb',
                        '    b  beb',
                        '    b  bbb',
                        '    b   kk',
                        ' bbbbbb   ',
                        ' bbsbbb   ',
                        ' bb   b   ',
                        'bbb   b   ',
                        'bb  bbb   ',
                        'bb  bbb   ',
                        ' bbbb     ',
                        '          '],
        'start': {'x': 4, 'y': 2},
        'swatches': [   {   'fields': [   {   'action': 'off',
                                              'position': {'x': 9, 'y': 6}},
                                          {   'action': 'off',
                                              'position': {'x': 8, 'y': 6}}],
                            'position': {'x': 3, 'y': 8},
                            'type': 's'}]},
    {   'geometry': [   '          ',
                        '  bb      ',
                        '  bbb     ',
                        '  bbb     ',
                        '  bbbbb   ',
                        '    beb   ',
                        'bb  bbbbb ',
                        'bbb  lbhb ',
                        'bbb   bbb ',
                        '  b    b  ',
                        '  bbb  b  ',
                        '  bbbbbbb ',
                        '   bbbbbb ',
                        '   bb  lbh',
                        '          '],
        'start': {'x': 3, 'y': 3},
        'swatches': [   {   'fields': [   {   'action': 'onoff',
                                              'position': {'x': 5, 'y': 7}}],
                            'position': {'x': 9, 'y': 13},
                            'type': 'h'},
                        {   'fields': [   {   'action': 'onoff',
                                              'position': {'x': 7, 'y': 13}}],
                            'position': {'x': 7, 'y': 7},
                            'type': 'h'}]},
    {   'geometry': [   '          ',
                        '    bbbbbb',
                        '    bbbbbb',
                        '  bbbbb  b',
                        'bbb  f   f',
                        'bbb  f   b',
                        'bfffff   b',
                        ' fffbbb  b',
                        ' fbfbeb  b',
                        'bfffbbb  f',
                        'bfff     b',
                        ' ffb    bb',
                        '   bbbbbbb',
                        '     bbbbb',
                        '     bbb  '],
        'start': {'x': 6, 'y': 13},
        'swatches': []},
    {   'geometry': [   '  bbbbbb  ',
                        ' bb   ll  ',
                        'bbb   rr  ',
                        'beb   bbb ',
                        'bbb   bbb ',
                        '      bbb ',
                        '       b  ',
                        '       b  ',
                        'bbbb   bbb',
                        'bbbb   bbb',
                        'bbbb   bbb',
                        'b  b   b  ',
                        'b  bbbhb  ',
                        'h  bbbbb  ',
                        '          '],
        'start': {'x': 7, 'y': 4},
        'swatches': [   {   'fields': [   {   'action': 'onoff',
                                              'position': {'x': 7, 'y': 1}},
                                          {   'action': 'onoff',
                                              'position': {'x': 7, 'y': 2}}],
                            'position': {'x': 6, 'y': 12},
                            'type': 'h'},
                        {   'fields': [   {   'action': 'onoff',
                                              'position': {'x': 6, 'y': 1}},
                                          {   'action': 'onoff',
                                              'position': {'x': 6, 'y': 2}}],
                            'position': {'x': 0, 'y': 13},
                            'type': 'h'}]},
    {   'geometry': [   'bbb  bbb  ',
                        'bbbbbbbb  ',
                        'bbb   bl  ',
                        ' b    br  ',
                        ' b    bbb ',
                        ' b      k ',
                        'bbb     q ',
                        'bbbbv  bbb',
                        'bbb   sbbb',
                        ' k     bbb',
                        ' q      l ',
                        'sbs     r ',
                        'beb    bhb',
                        'bbb    bbb',
                        '       bbb'],
        'start': {'x': 1, 'y': 1},
        'swatches': [   {   'fields': [   {   'action': 'onoff',
                                              'position': {'x': 7, 'y': 2}},
                                          {   'action': 'onoff',
                                              'position': {'x': 7, 'y': 3}},
                                          {   'action': 'onoff',
                                              'position': {'x': 8, 'y': 5}},
                                          {   'action': 'onoff',
                                              'position': {'x': 8, 'y': 6}}],
                            'position': {'x': 8, 'y': 12},
                            'type': 'h'},
                        {   'fields': [   {   'action': 'onoff',
                                              'position': {'x': 8, 'y': 5}},
                                          {   'action': 'onoff',
                                              'position': {'x': 8, 'y': 6}},
                                          {   'action': 'onoff',
                                              'position': {'x': 8, 'y': 10}},
                                          {   'action': 'onoff',
                                              'position': {'x': 8, 'y': 11}}],
                            'position': {'x': 6, 'y': 8},
                            'type': 's'},
                        {   'fields': [   {   'action': 'split1',
                                              'position': {'x': 8, 'y': 13}},
                                          {   'action': 'split2',
                                              'position': {'x': 1, 'y': 1}}],
                            'position': {'x': 4, 'y': 7},
                            'type': 'v'},
                        {   'fields': [   {   'action': 'off',
                                              'position': {'x': 1, 'y': 9}},
                                          {   'action': 'off',
                                              'position': {'x': 1, 'y': 10}}],
                            'position': {'x': 2, 'y': 11},
                            'type': 's'},
                        {   'fields': [   {   'action': 'off',
                                              'position': {'x': 1, 'y': 9}},
                                          {   'action': 'off',
                                              'position': {'x': 1, 'y': 10}}],
                            'position': {'x': 0, 'y': 11},
                            'type': 's'}]},
    {   'geometry': [   '      v   ',
                        '     vbv  ',
                        'bbb   v   ',
                        'bbb   l   ',
                        'bbb   r   ',
                        ' b    h   ',
                        ' b    h   ',
                        ' b    b   ',
                        'bbb   l   ',
                        'bvb   r   ',
                        'bbb  bbb  ',
                        '     beb  ',
                        '     bbb  ',
                        '          ',
                        '          '],
        'start': {'x': 1, 'y': 3},
        'swatches': [   {   'fields': [   {   'action': 'split1',
                                              'position': {'x': 6, 'y': 7}},
                                          {   'action': 'split2',
                                              'position': {'x': 6, 'y': 5}}],
                            'position': {'x': 7, 'y': 1},
                            'type': 'v'},
                        {   'fields': [   {   'action': 'split1',
                                              'position': {'x': 6, 'y': 2}},
                                          {   'action': 'split2',
                                              'position': {'x': 7, 'y': 1}}],
                            'position': {'x': 6, 'y': 0},
                            'type': 'v'},
                        {   'fields': [   {   'action': 'split1',
                                              'position': {'x': 6, 'y': 0}},
                                          {   'action': 'split2',
                                              'position': {'x': 6, 'y': 2}}],
                            'position': {'x': 6, 'y': 2},
                            'type': 'v'},
                        {   'fields': [   {   'action': 'on',
                                              'position': {'x': 6, 'y': 3}},
                                          {   'action': 'on',
                                              'position': {'x': 6, 'y': 4}}],
                            'position': {'x': 6, 'y': 5},
                            'type': 'h'},
                        {   'fields': [   {   'action': 'on',
                                              'position': {'x': 6, 'y': 8}},
                                          {   'action': 'on',
                                              'position': {'x': 6, 'y': 9}}],
                            'position': {'x': 6, 'y': 6},
                            'type': 'h'},
                        {   'fields': [   {   'action': 'split1',
                                              'position': {'x': 5, 'y': 1}},
                                          {   'action': 'split2',
                                              'position': {'x': 6, 'y': 0}}],
                            'position': {'x': 5, 'y': 1},
                            'type': 'v'},
                        {   'fields': [   {   'action': 'split1',
                                              'position': {'x': 7, 'y': 1}},
                                          {   'action': 'split2',
                                              'position': {'x': 6, 'y': 0}}],
                            'position': {'x': 1, 'y': 9},
                            'type': 'v'}]},
    {   'geometry': [   'bbbbbbbbbb',
                        'bsbbbbbbbb',
                        'bbbbbbbbbb',
                        '  b     b ',
                        '  b     b ',
                        '  b     b ',
                        '  br    b ',
                        '  bb   rb ',
                        '  lb   bb ',
                        '   b   bl ',
                        '   b   b  ',
                        'bbbb   b  ',
                        'hbbh  hbb ',
                        '      heb ',
                        '      bbb '],
        'start': {'x': 8, 'y': 1},
        'swatches': [   {   'fields': [   {   'action': 'off',
                                              'position': {'x': 3, 'y': 6}}],
                            'position': {'x': 6, 'y': 12},
                            'type': 'h'},
                        {   'fields': [   {   'action': 'on',
                                              'position': {'x': 3, 'y': 6}}],
                            'position': {'x': 6, 'y': 13},
                            'type': 'h'},
                        {   'fields': [   {   'action': 'on',
                                              'position': {'x': 7, 'y': 7}}],
                            'position': {'x': 3, 'y': 12},
                            'type': 'h'},
                        {   'fields': [   {   'action': 'onoff',
                                              'position': {'x': 2, 'y': 8}}],
                            'position': {'x': 1, 'y': 1},
                            'type': 's'},
                        {   'fields': [   {   'action': 'on',
                                              'position': {'x': 8, 'y': 9}},
                                          {   'action': 'off',
                                              'position': {'x': 2, 'y': 8}}],
                            'position': {'x': 0, 'y': 12},
                            'type': 'h'}]},
    {   'geometry': [   'bbbbbbbb  ',
                        'l  bbsbb  ',
                        'r  sbbbs  ',
                        'h  bbbbb  ',
                        '    bbb   ',
                        '    lb    ',
                        '     b    ',
                        '     bbbs ',
                        '  sbbl    ',
                        '     r    ',
                        'bb   b    ',
                        'bbb  b    ',
                        'bebbbl    ',
                        'bbb  r    ',
                        '     b    '],
        'start': {'x': 5, 'y': 2},
        'swatches': [   {   'fields': [   {   'action': 'on',
                                              'position': {'x': 5, 'y': 8}},
                                          {   'action': 'on',
                                              'position': {'x': 5, 'y': 9}}],
                            'position': {'x': 8, 'y': 7},
                            'type': 's'},
                        {   'fields': [   {   'action': 'off',
                                              'position': {'x': 5, 'y': 12}},
                                          {   'action': 'off',
                                              'position': {'x': 5, 'y': 13}},
                                          {   'action': 'off',
                                              'position': {'x': 0, 'y': 1}},
                                          {   'action': 'off',
                                              'position': {'x': 0, 'y': 2}}],
                            'position': {'x': 7, 'y': 2},
                            'type': 's'},
                        {   'fields': [   {   'action': 'off',
                                              'position': {'x': 5, 'y': 8}},
                                          {   'action': 'off',
                                              'position': {'x': 5, 'y': 9}}],
                            'position': {'x': 5, 'y': 1},
                            'type': 's'},
                        {   'fields': [   {   'action': 'off',
                                              'position': {'x': 5, 'y': 12}},
                                          {   'action': 'off',
                                              'position': {'x': 5, 'y': 13}},
                                          {   'action': 'off',
                                              'position': {'x': 0, 'y': 1}},
                                          {   'action': 'off',
                                              'position': {'x': 0, 'y': 2}}],
                            'position': {'x': 3, 'y': 2},
                            'type': 's'},
                        {   'fields': [   {   'action': 'on',
                                              'position': {'x': 5, 'y': 12}},
                                          {   'action': 'on',
                                              'position': {'x': 5, 'y': 13}},
                                          {   'action': 'on',
                                              'position': {'x': 0, 'y': 1}},
                                          {   'action': 'on',
                                              'position': {'x': 0, 'y': 2}}],
                            'position': {'x': 2, 'y': 8},
                            'type': 's'},
                        {   'fields': [   {   'action': 'onoff',
                                              'position': {'x': 4, 'y': 5}}],
                            'position': {'x': 0, 'y': 3},
                            'type': 'h'}]},
    {   'geometry': [   '  bbb     ',
                        'bbbeb    b',
                        'kbbbb    b',
                        'q        b',
                        'b        b',
                        'bbbbb  bbb',
                        'bbbbb  bbb',
                        'b   l    b',
                        'b   r    b',
                        'b   b    b',
                        's   s    s',
                        'b   b    b',
                        'b   b    b',
                        'b   bbbbbb',
                        '    bbbbbb'],
        'start': {'x': 9, 'y': 1},
        'swatches': [   {   'fields': [   {   'action': 'onoff',
                                              'position': {'x': 4, 'y': 7}},
                                          {   'action': 'onoff',
                                              'position': {'x': 4, 'y': 8}}],
                            'position': {'x': 9, 'y': 10},
                            'type': 's'},
                        {   'fields': [   {   'action': 'off',
                                              'position': {'x': 0, 'y': 2}},
                                          {   'action': 'off',
                                              'position': {'x': 0, 'y': 3}}],
                            'position': {'x': 4, 'y': 10},
                            'type': 's'},
                        {   'fields': [   {   'action': 'on',
                                              'position': {'x': 0, 'y': 2}},
                                          {   'action': 'on',
                                              'position': {'x': 0, 'y': 3}}],
                            'position': {'x': 0, 'y': 10},
                            'type': 's'}]},
    {   'geometry': [   '  bb      ',
                        '  sb      ',
                        '   bbbbbb ',
                        '   bbsbbb ',
                        '    bbbbb ',
                        '        k ',
                        '        q ',
                        '   bbvbsb ',
                        '   bbbbbb ',
                        '   bbsbbb ',
                        '   l    l ',
                        '   r    r ',
                        'bbbs   bbb',
                        'bebb   bbb',
                        'bbbb   bbb'],
        'start': {'x': 7, 'y': 8},
        'swatches': [   {   'fields': [   {   'action': 'off',
                                              'position': {'x': 8, 'y': 5}},
                                          {   'action': 'off',
                                              'position': {'x': 8, 'y': 6}}],
                            'position': {'x': 7, 'y': 7},
                            'type': 's'},
                        {   'fields': [   {   'action': 'off',
                                              'position': {'x': 8, 'y': 5}},
                                          {   'action': 'off',
                                              'position': {'x': 8, 'y': 6}}],
                            'position': {'x': 5, 'y': 3},
                            'type': 's'},
                        {   'fields': [   {   'action': 'split1',
                                              'position': {'x': 8, 'y': 13}},
                                          {   'action': 'split2',
                                              'position': {'x': 2, 'y': 13}}],
                            'position': {'x': 5, 'y': 7},
                            'type': 'v'},
                        {   'fields': [   {   'action': 'off',
                                              'position': {'x': 8, 'y': 5}},
                                          {   'action': 'off',
                                              'position': {'x': 8, 'y': 6}}],
                            'position': {'x': 5, 'y': 9},
                            'type': 's'},
                        {   'fields': [   {   'action': 'onoff',
                                              'position': {'x': 3, 'y': 10}},
                                          {   'action': 'onoff',
                                              'position': {'x': 3, 'y': 11}}],
                            'position': {'x': 3, 'y': 12},
                            'type': 's'},
                        {   'fields': [   {   'action': 'onoff',
                                              'position': {'x': 8, 'y': 10}},
                                          {   'action': 'onoff',
                                              'position': {'x': 8, 'y': 11}}],
                            'position': {'x': 2, 'y': 1},
                            'type': 's'}]},
    {   'geometry': [   '     bbb  ',
                        '    bbbb  ',
                        '  bbbbb   ',
                        'rbb  bb   ',
                        'bbb   bb  ',
                        'bbl   bb  ',
                        'b      b  ',
                        'b      bb ',
                        'bbbhhbbbbb',
                        'bbbbb  bbb',
                        '    b     ',
                        '    b     ',
                        '   bbb    ',
                        '   beb    ',
                        '   bbb    '],
        'start': {'x': 6, 'y': 1},
        'swatches': [   {   'fields': [   {   'action': 'onoff',
                                              'position': {'x': 0, 'y': 3}}],
                            'position': {'x': 4, 'y': 8},
                            'type': 'h'},
                        {   'fields': [   {   'action': 'onoff',
                                              'position': {'x': 2, 'y': 5}}],
                            'position': {'x': 3, 'y': 8},
                            'type': 'h'}]},
    {   'geometry': [   '          ',
                        '     bbb  ',
                        ' bbbbbbb  ',
                        'hbl  bbb  ',
                        '      bbb ',
                        '      sbb ',
                        '       bbb',
                        '       sbb',
                        '      bbb ',
                        '      bbb ',
                        'hbq  bbb  ',
                        ' bbbbbbb  ',
                        '     bbbbb',
                        '      lbeb',
                        '       bbb'],
        'start': {'x': 6, 'y': 2},
        'swatches': [   {   'fields': [   {   'action': 'off',
                                              'position': {'x': 2, 'y': 3}},
                                          {   'action': 'off',
                                              'position': {'x': 6, 'y': 13}}],
                            'position': {'x': 7, 'y': 7},
                            'type': 's'},
                        {   'fields': [   {   'action': 'off',
                                              'position': {'x': 2, 'y': 3}},
                                          {   'action': 'off',
                                              'position': {'x': 6, 'y': 13}}],
                            'position': {'x': 6, 'y': 5},
                            'type': 's'},
                        {   'fields': [   {   'action': 'onoff',
                                              'position': {'x': 6, 'y': 13}}],
                            'position': {'x': 0, 'y': 3},
                            'type': 'h'},
                        {   'fields': [   {   'action': 'onoff',
                                              'position': {'x': 2, 'y': 3}}],
                            'position': {'x': 0, 'y': 10},
                            'type': 'h'}]},
    {   'geometry': [   '   bsbr   ',
                        '   l  bbbb',
                        '   r  bbhb',
                        'bbbb  bbbb',
                        'bbbbbbl   ',
                        'bbbb      ',
                        'bfff      ',
                        'bffffbbb  ',
                        'lffffbeb  ',
                        ' ffffbbb  ',
                        ' fff   k  ',
                        ' bbb   q  ',
                        ' bvb  bbbb',
                        ' bbb  bbsb',
                        '   kbbsbbb'],
        'start': {'x': 2, 'y': 4},
        'swatches': [   {   'fields': [   {   'action': 'on',
                                              'position': {'x': 6, 'y': 4}}],
                            'position': {'x': 8, 'y': 2},
                            'type': 'h'},
                        {   'fields': [   {   'action': 'onoff',
                                              'position': {'x': 0, 'y': 8}},
                                          {   'action': 'on',
                                              'position': {'x': 3, 'y': 1}},
                                          {   'action': 'on',
                                              'position': {'x': 3, 'y': 2}}],
                            'position': {'x': 8, 'y': 13},
                            'type': 's'},
                        {   'fields': [   {   'action': 'off',
                                              'position': {'x': 3, 'y': 14}},
                                          {   'action': 'off',
                                              'position': {'x': 7, 'y': 10}},
                                          {   'action': 'off',
                                              'position': {'x': 7, 'y': 11}}],
                            'position': {'x': 6, 'y': 14},
                            'type': 's'},
                        {   'fields': [   {   'action': 'on',
                                              'position': {'x': 6, 'y': 0}},
                                          {   'action': 'off',
                                              'position': {'x': 3, 'y': 1}},
                                          {   'action': 'off',
                                              'position': {'x': 3, 'y': 2}}],
                            'position': {'x': 4, 'y': 0},
                            'type': 's'},
                        {   'fields': [   {   'action': 'split1',
                                              'position': {'x': 2, 'y': 12}},
                                          {   'action': 'split2',
                                              'position': {'x': 7, 'y': 2}}],
                            'position': {'x': 2, 'y': 12},
                            'type': 'v'}]},
    {   'geometry': [   '          ',
                        '  bbbh    ',
                        '  bbbbb   ',
                        '  bb  l   ',
                        '   b  rr  ',
                        '   bbbbb  ',
                        ' hb  bhb  ',
                        ' bb   bb  ',
                        ' lb    b  ',
                        '  l    b  ',
                        '  r    b  ',
                        ' bbb  bbb ',
                        ' beb  bhb ',
                        ' bbbbbbbb ',
                        '      bvb '],
        'start': {'x': 6, 'y': 2},
        'swatches': [   {   'fields': [   {   'action': 'on',
                                              'position': {'x': 6, 'y': 4}},
                                          {   'action': 'on',
                                              'position': {'x': 6, 'y': 3}}],
                            'position': {'x': 7, 'y': 12},
                            'type': 'h'},
                        {   'fields': [   {   'action': 'split1',
                                              'position': {'x': 2, 'y': 6}},
                                          {   'action': 'split2',
                                              'position': {'x': 2, 'y': 8}}],
                            'position': {'x': 7, 'y': 14},
                            'type': 'v'},
                        {   'fields': [   {   'action': 'on',
                                              'position': {'x': 1, 'y': 8}}],
                            'position': {'x': 6, 'y': 6},
                            'type': 'h'},
                        {   'fields': [   {   'action': 'on',
                                              'position': {'x': 7, 'y': 4}}],
                            'position': {'x': 5, 'y': 1},
                            'type': 'h'},
                        {   'fields': [   {   'action': 'on',
                                              'position': {'x': 2, 'y': 9}},
                                          {   'action': 'on',
                                              'position': {'x': 2, 'y': 10}}],
                            'position': {'x': 1, 'y': 6},
                            'type': 'h'}]},
    {   'geometry': [   ' bbb      ',
                        ' bbbb     ',
                        ' kkhb  bbb',
                        '   b  bbbb',
                        '   k  bsb ',
                        '   q  b   ',
                        ' bbbbbb   ',
                        ' bbbbbl   ',
                        ' s   l    ',
                        ' b   r    ',
                        ' b   bbb  ',
                        'bbb  beb  ',
                        'bbb  bbb  ',
                        'bbb   ll  ',
                        '          '],
        'start': {'x': 2, 'y': 1},
        'swatches': [   {   'fields': [   {   'action': 'onoff',
                                              'position': {'x': 7, 'y': 13}},
                                          {   'action': 'onoff',
                                              'position': {'x': 6, 'y': 13}},
                                          {   'action': 'onoff',
                                              'position': {'x': 5, 'y': 8}},
                                          {   'action': 'onoff',
                                              'position': {'x': 5, 'y': 9}}],
                            'position': {'x': 7, 'y': 4},
                            'type': 's'},
                        {   'fields': [   {   'action': 'on',
                                              'position': {'x': 5, 'y': 8}},
                                          {   'action': 'on',
                                              'position': {'x': 5, 'y': 9}}],
                            'position': {'x': 3, 'y': 2},
                            'type': 'h'},
                        {   'fields': [   {   'action': 'on',
                                              'position': {'x': 6, 'y': 7}},
                                          {   'action': 'off',
                                              'position': {'x': 3, 'y': 4}},
                                          {   'action': 'off',
                                              'position': {'x': 3, 'y': 5}}],
                            'position': {'x': 1, 'y': 8},
                            'type': 's'}]},
    {   'geometry': [   '    bbb   ',
                        '  hbbbb   ',
                        '    bbk   ',
                        '     lq   ',
                        '      bb  ',
                        '      bbbb',
                        ' bbbbbbbbb',
                        ' beb  bbsb',
                        ' bbb   bbb',
                        '  l    bb ',
                        '    bbbbb ',
                        '     bb   ',
                        '      b   ',
                        '      bbbv',
                        '          '],
        'start': {'x': 4, 'y': 10},
        'swatches': [   {   'fields': [   {   'action': 'split1',
                                              'position': {'x': 6, 'y': 12}},
                                          {   'action': 'split2',
                                              'position': {'x': 4, 'y': 10}}],
                            'position': {'x': 9, 'y': 13},
                            'type': 'v'},
                        {   'fields': [   {   'action': 'off',
                                              'position': {'x': 6, 'y': 2}},
                                          {   'action': 'off',
                                              'position': {'x': 6, 'y': 3}}],
                            'position': {'x': 8, 'y': 7},
                            'type': 's'},
                        {   'fields': [   {   'action': 'on',
                                              'position': {'x': 2, 'y': 9}},
                                          {   'action': 'on',
                                              'position': {'x': 5, 'y': 3}}],
                            'position': {'x': 2, 'y': 1},
                            'type': 'h'}]},
    {   'geometry': [   '  bbb  bbb',
                        '  beb  bbb',
                        '  bbb  bbb',
                        '  ff    b ',
                        '  ff    b ',
                        ' ffff   b ',
                        'qffff   b ',
                        'bffff  bbb',
                        'bffff  bbb',
                        'kfffb   bb',
                        ' ff     bb',
                        ' ff      b',
                        ' bbbsbb  b',
                        ' bbbsbhbbb',
                        ' bbb  bbbb'],
        'start': {'x': 8, 'y': 1},
        'swatches': [   {   'fields': [   {   'action': 'off',
                                              'position': {'x': 0, 'y': 6}},
                                          {   'action': 'off',
                                              'position': {'x': 0, 'y': 9}}],
                            'position': {'x': 6, 'y': 13},
                            'type': 'h'},
                        {   'fields': [   {   'action': 'off',
                                              'position': {'x': 0, 'y': 6}}],
                            'position': {'x': 4, 'y': 12},
                            'type': 's'},
                        {   'fields': [   {   'action': 'off',
                                              'position': {'x': 0, 'y': 9}}],
                            'position': {'x': 4, 'y': 13},
                            'type': 's'}]},
    {   'geometry': [   '    ffff  ',
                        '  bbbfffbb',
                        'bbbeb  bbb',
                        '  bbb    k',
                        '  b      q',
                        'bbb    bbb',
                        'bbb    bbb',
                        'b     bbb ',
                        'k    bbb  ',
                        'q   bbb   ',
                        'bbbbbb    ',
                        'bbsbv     ',
                        'bbbb      ',
                        '  bb      ',
                        '  bb      '],
        'start': {'x': 7, 'y': 2},
        'swatches': [   {   'fields': [   {   'action': 'split1',
                                              'position': {'x': 3, 'y': 14}},
                                          {   'action': 'split2',
                                              'position': {'x': 0, 'y': 12}}],
                            'position': {'x': 4, 'y': 11},
                            'type': 'v'},
                        {   'fields': [   {   'action': 'off',
                                              'position': {'x': 9, 'y': 4}},
                                          {   'action': 'off',
                                              'position': {'x': 9, 'y': 3}},
                                          {   'action': 'off',
                                              'position': {'x': 0, 'y': 8}},
                                          {   'action': 'off',
                                              'position': {'x': 0, 'y': 9}}],
                            'position': {'x': 2, 'y': 11},
                            'type': 's'}]},
    {   'geometry': [   'bbb   h   ',
                        'beb   l   ',
                        'bbb   r  s',
                        'll    b  k',
                        ' r    b  q',
                        ' bbrrbbbbb',
                        '  bbbbbb  ',
                        '     bbb  ',
                        '     bbb  ',
                        'bbbbbbbbbb',
                        'k  k  b  l',
                        'q  q  b  r',
                        's  s  l  h',
                        '      r   ',
                        '      h   '],
        'start': {'x': 6, 'y': 7},
        'swatches': [   {   'fields': [   {   'action': 'on',
                                              'position': {'x': 9, 'y': 10}},
                                          {   'action': 'on',
                                              'position': {'x': 9, 'y': 11}},
                                          {   'action': 'off',
                                              'position': {'x': 3, 'y': 10}},
                                          {   'action': 'off',
                                              'position': {'x': 3, 'y': 11}}],
                            'position': {'x': 9, 'y': 2},
                            'type': 's'},
                        {   'fields': [   {   'action': 'on',
                                              'position': {'x': 4, 'y': 5}},
                                          {   'action': 'on',
                                              'position': {'x': 3, 'y': 5}}],
                            'position': {'x': 9, 'y': 12},
                            'type': 'h'},
                        {   'fields': [   {   'action': 'on',
                                              'position': {'x': 1, 'y': 3}},
                                          {   'action': 'on',
                                              'position': {'x': 1, 'y': 4}},
                                          {   'action': 'off',
                                              'position': {'x': 0, 'y': 10}},
                                          {   'action': 'off',
                                              'position': {'x': 0, 'y': 11}}],
                            'position': {'x': 6, 'y': 0},
                            'type': 'h'},
                        {   'fields': [   {   'action': 'on',
                                              'position': {'x': 0, 'y': 3}}],
                            'position': {'x': 6, 'y': 14},
                            'type': 'h'},
                        {   'fields': [   {   'action': 'on',
                                              'position': {'x': 6, 'y': 1}},
                                          {   'action': 'on',
                                              'position': {'x': 6, 'y': 2}}],
                            'position': {'x': 3, 'y': 12},
                            'type': 's'},
                        {   'fields': [   {   'action': 'on',
                                              'position': {'x': 6, 'y': 12}},
                                          {   'action': 'on',
                                              'position': {'x': 6, 'y': 13}},
                                          {   'action': 'off',
                                              'position': {'x': 3, 'y': 10}},
                                          {   'action': 'off',
                                              'position': {'x': 3, 'y': 11}},
                                          {   'action': 'off',
                                              'position': {'x': 9, 'y': 3}},
                                          {   'action': 'off',
                                              'position': {'x': 9, 'y': 4}},
                                          {   'action': 'off',
                                              'position': {'x': 9, 'y': 10}},
                                          {   'action': 'off',
                                              'position': {'x': 9, 'y': 11}}],
                            'position': {'x': 0, 'y': 12},
                            'type': 's'}]},
    {   'geometry': [   ' bff      ',
                        'ffffh     ',
                        'bfffbb    ',
                        'ffbff  bbb',
                        'fff    beb',
                        'ffb    bbb',
                        ' ff     bb',
                        ' ffbfff  b',
                        'ffbbffb  f',
                        'fffl  b  f',
                        'ff    k  b',
                        'ff    q  b',
                        'bbhr  bffb',
                        '  bb  bbbb',
                        '  lbbbbh  '],
        'start': {'x': 5, 'y': 2},
        'swatches': [   {   'fields': [   {   'action': 'off',
                                              'position': {'x': 6, 'y': 10}},
                                          {   'action': 'off',
                                              'position': {'x': 6, 'y': 11}},
                                          {   'action': 'on',
                                              'position': {'x': 3, 'y': 9}},
                                          {   'action': 'on',
                                              'position': {'x': 3, 'y': 12}}],
                            'position': {'x': 7, 'y': 14},
                            'type': 'h'},
                        {   'fields': [   {   'action': 'on',
                                              'position': {'x': 6, 'y': 10}},
                                          {   'action': 'on',
                                              'position': {'x': 6, 'y': 11}}],
                            'position': {'x': 4, 'y': 1},
                            'type': 'h'},
                        {   'fields': [   {   'action': 'onoff',
                                              'position': {'x': 2, 'y': 14}}],
                            'position': {'x': 2, 'y': 12},
                            'type': 'h'}]},
    {   'geometry': [   'qqq       ',
                        'bbb  fbbb ',
                        'bhbbffbbb ',
                        'bbb  fbbb ',
                        '  l    k  ',
                        '  r    q  ',
                        ' hbbbsbb  ',
                        '  sbbbbb  ',
                        '  bbbbbbh ',
                        '  k    l  ',
                        '  q    r  ',
                        ' bbbf  bbb',
                        ' bbbffbbeb',
                        ' bbbf  bbb',
                        '       lll'],
        'start': {'x': 2, 'y': 12},
        'swatches': [   {   'fields': [   {   'action': 'onoff',
                                              'position': {'x': 7, 'y': 9}},
                                          {   'action': 'onoff',
                                              'position': {'x': 7, 'y': 10}}],
                            'position': {'x': 8, 'y': 8},
                            'type': 'h'},
                        {   'fields': [   {   'action': 'off',
                                              'position': {'x': 7, 'y': 4}},
                                          {   'action': 'off',
                                              'position': {'x': 7, 'y': 5}},
                                          {   'action': 'off',
                                              'position': {'x': 7, 'y': 9}},
                                          {   'action': 'off',
                                              'position': {'x': 7, 'y': 10}},
                                          {   'action': 'off',
                                              'position': {'x': 2, 'y': 4}},
                                          {   'action': 'off',
                                              'position': {'x': 2, 'y': 5}},
                                          {   'action': 'off',
                                              'position': {'x': 2, 'y': 9}},
                                          {   'action': 'off',
                                              'position': {'x': 2, 'y': 10}}],
                            'position': {'x': 5, 'y': 6},
                            'type': 's'},
                        {   'fields': [   {   'action': 'off',
                                              'position': {'x': 7, 'y': 4}},
                                          {   'action': 'off',
                                              'position': {'x': 7, 'y': 5}},
                                          {   'action': 'off',
                                              'position': {'x': 7, 'y': 9}},
                                          {   'action': 'off',
                                              'position': {'x': 7, 'y': 10}},
                                          {   'action': 'off',
                                              'position': {'x': 2, 'y': 4}},
                                          {   'action': 'off',
                                              'position': {'x': 2, 'y': 5}},
                                          {   'action': 'off',
                                              'position': {'x': 2, 'y': 9}},
                                          {   'action': 'off',
                                              'position': {'x': 2, 'y': 10}}],
                            'position': {'x': 2, 'y': 7},
                            'type': 's'},
                        {   'fields': [   {   'action': 'on',
                                              'position': {'x': 7, 'y': 14}},
                                          {   'action': 'on',
                                              'position': {'x': 8, 'y': 14}},
                                          {   'action': 'on',
                                              'position': {'x': 9, 'y': 14}},
                                          {   'action': 'off',
                                              'position': {'x': 7, 'y': 4}},
                                          {   'action': 'off',
                                              'position': {'x': 7, 'y': 5}}],
                            'position': {'x': 1, 'y': 2},
                            'type': 'h'},
                        {   'fields': [   {   'action': 'onoff',
                                              'position': {'x': 2, 'y': 4}},
                                          {   'action': 'onoff',
                                              'position': {'x': 2, 'y': 5}}],
                            'position': {'x': 1, 'y': 6},
                            'type': 'h'}]},
    {   'geometry': [   '          ',
                        ' bb       ',
                        ' bb  bbb  ',
                        ' ll  bebb ',
                        ' rr  bbbb ',
                        ' bbb   lk ',
                        ' bhb   rq ',
                        ' bbb   bb ',
                        ' b    bbb ',
                        ' b   bb   ',
                        ' bbbbbb   ',
                        ' bbbbbbb  ',
                        '      bhb ',
                        '       bbb',
                        '       bbh'],
        'start': {'x': 3, 'y': 11},
        'swatches': [   {   'fields': [   {   'action': 'onoff',
                                              'position': {'x': 2, 'y': 3}},
                                          {   'action': 'onoff',
                                              'position': {'x': 2, 'y': 4}},
                                          {   'action': 'onoff',
                                              'position': {'x': 8, 'y': 5}},
                                          {   'action': 'onoff',
                                              'position': {'x': 8, 'y': 6}}],
                            'position': {'x': 9, 'y': 14},
                            'type': 'h'},
                        {   'fields': [   {   'action': 'onoff',
                                              'position': {'x': 1, 'y': 3}},
                                          {   'action': 'onoff',
                                              'position': {'x': 1, 'y': 4}}],
                            'position': {'x': 7, 'y': 12},
                            'type': 'h'},
                        {   'fields': [   {   'action': 'onoff',
                                              'position': {'x': 7, 'y': 5}},
                                          {   'action': 'onoff',
                                              'position': {'x': 7, 'y': 6}}],
                            'position': {'x': 2, 'y': 6},
                            'type': 'h'}]},
    {   'geometry': [   'bbbb  bb  ',
                        'bbeb  bb  ',
                        'bbbb  bb  ',
                        '  k   k   ',
                        '  q   q   ',
                        ' bbbbbbsbb',
                        ' bsbbbbbbb',
                        ' bbbbsbbbs',
                        '   bbbbsbb',
                        '   bbbsbbb',
                        '  bbbssbbb',
                        ' bbssbbbl ',
                        'bbbbbbbb  ',
                        'bbsbbbsb  ',
                        'bbhb      '],
        'start': {'x': 6, 'y': 1},
        'swatches': [   {   'fields': [   {   'action': 'off',
                                              'position': {'x': 2, 'y': 3}},
                                          {   'action': 'off',
                                              'position': {'x': 2, 'y': 4}}],
                            'position': {'x': 9, 'y': 7},
                            'type': 's'},
                        {   'fields': [   {   'action': 'off',
                                              'position': {'x': 2, 'y': 3}},
                                          {   'action': 'off',
                                              'position': {'x': 2, 'y': 4}}],
                            'position': {'x': 7, 'y': 5},
                            'type': 's'},
                        {   'fields': [   {   'action': 'off',
                                              'position': {'x': 2, 'y': 3}},
                                          {   'action': 'off',
                                              'position': {'x': 2, 'y': 4}}],
                            'position': {'x': 7, 'y': 8},
                            'type': 's'},
                        {   'fields': [   {   'action': 'off',
                                              'position': {'x': 2, 'y': 3}},
                                          {   'action': 'off',
                                              'position': {'x': 2, 'y': 4}}],
                            'position': {'x': 6, 'y': 9},
                            'type': 's'},
                        {   'fields': [   {   'action': 'off',
                                              'position': {'x': 2, 'y': 3}},
                                          {   'action': 'off',
                                              'position': {'x': 2, 'y': 4}}],
                            'position': {'x': 6, 'y': 10},
                            'type': 's'},
                        {   'fields': [   {   'action': 'off',
                                              'position': {'x': 2, 'y': 3}},
                                          {   'action': 'off',
                                              'position': {'x': 2, 'y': 4}}],
                            'position': {'x': 6, 'y': 13},
                            'type': 's'},
                        {   'fields': [   {   'action': 'off',
                                              'position': {'x': 2, 'y': 3}},
                                          {   'action': 'off',
                                              'position': {'x': 2, 'y': 4}}],
                            'position': {'x': 5, 'y': 7},
                            'type': 's'},
                        {   'fields': [   {   'action': 'off',
                                              'position': {'x': 2, 'y': 3}},
                                          {   'action': 'off',
                                              'position': {'x': 2, 'y': 4}}],
                            'position': {'x': 5, 'y': 10},
                            'type': 's'},
                        {   'fields': [   {   'action': 'off',
                                              'position': {'x': 2, 'y': 3}},
                                          {   'action': 'off',
                                              'position': {'x': 2, 'y': 4}}],
                            'position': {'x': 4, 'y': 11},
                            'type': 's'},
                        {   'fields': [   {   'action': 'off',
                                              'position': {'x': 2, 'y': 3}},
                                          {   'action': 'off',
                                              'position': {'x': 2, 'y': 4}}],
                            'position': {'x': 3, 'y': 11},
                            'type': 's'},
                        {   'fields': [   {   'action': 'off',
                                              'position': {'x': 2, 'y': 3}},
                                          {   'action': 'off',
                                              'position': {'x': 2, 'y': 4}}],
                            'position': {'x': 2, 'y': 6},
                            'type': 's'},
                        {   'fields': [   {   'action': 'off',
                                              'position': {'x': 2, 'y': 3}},
                                          {   'action': 'off',
                                              'position': {'x': 2, 'y': 4}}],
                            'position': {'x': 2, 'y': 13},
                            'type': 's'},
                        {   'fields': [   {   'action': 'on',
                                              'position': {'x': 8, 'y': 11}}],
                            'position': {'x': 2, 'y': 14},
                            'type': 'h'}]}]
