// generated by buildrom.sh from games/games.txt
#define GAME_FIRST_BANK 2
#define GAME_COUNT 14
static char *const gameNames[GAME_COUNT] = {
    "  ARMOR ATTACK\x80",
    "  BERZERK\x80",
    "  BLITZ\x80",
    "  COSMIC CHASM\x80",
    "  FORTRESS NARZOD\x80",
    "  HYPERCHASE\x80",
    "  KARL QUAPPE\x80",
    "  POLE POSITION\x80",
    "  RIP-OFF\x80",
    "  SCRAMBLE\x80",
    "  SOLAR QUEST\x80",
    "  SPIKE\x80",
    "  STAR CASTLE\x80",
    "  WEB WARP\x80",
};
static char *const selectedGameNames[GAME_COUNT] = {
    "> ARMOR ATTACK\x80",
    "> BERZERK\x80",
    "> BLITZ\x80",
    "> COSMIC CHASM\x80",
    "> FORTRESS NARZOD\x80",
    "> HYPERCHASE\x80",
    "> KARL QUAPPE\x80",
    "> POLE POSITION\x80",
    "> RIP-OFF\x80",
    "> SCRAMBLE\x80",
    "> SOLAR QUEST\x80",
    "> SPIKE\x80",
    "> STAR CASTLE\x80",
    "> WEB WARP\x80",
};
